#!/bin/bash
set -e

NGINX_VERSION=1.7.10
RTMP_VERSION=1.1.5
NPS_VERSION=1.9.32.3

# use maximum available processor cores for the build
alias make="make -j$(awk '/^processor/ { N++} END { print N }' /proc/cpuinfo)"

cd /tmp/nginx

./configure --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --sbin-path=/usr/sbin \
  --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log \
  --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid \
  --http-client-body-temp-path=/var/lib/nginx/body \
  --http-fastcgi-temp-path=/var/lib/nginx/fastcgi \
  --http-proxy-temp-path=/var/lib/nginx/proxy \
  --http-scgi-temp-path=/var/lib/nginx/scgi \
  --http-uwsgi-temp-path=/var/lib/nginx/uwsgi \
  --with-pcre-jit --with-ipv6 --with-http_ssl_module \
  --with-http_stub_status_module --with-http_realip_module \
  --with-http_addition_module --with-http_dav_module --with-http_geoip_module \
  --with-http_gzip_static_module --with-http_image_filter_module \
  --with-http_spdy_module --with-http_sub_module --with-http_xslt_module \
  --with-mail --with-mail_ssl_module \
  --add-module=/tmp/nginx-rtmp-module \
  --add-module=/tmp/ngx_pagespeed
make && make install
cp /tmp/nginx-rtmp-module/stat.xsl /usr/share/nginx/html/

# purge build dependencies
apt-get purge -y --auto-remove gcc g++ make libc6-dev libpcre++-dev libssl-dev libxslt-dev libgd2-xpm-dev libgeoip-dev

# cleanup
rm -rf /tmp/nginx /tmp/nginx-rtmp-module /tmp/ngx_pagespeed
rm -rf /var/lib/apt/lists/*
